site_name: Metabolomics Hub
site_url: https://metabolomicshub.org/site
theme:
  name: material
  logo: assets/mhd-logo.png
  favicon: assets/favicon.ico
  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - toc.integrate
extra:
  social:
  - icon: fontawesome/brands/x-twitter
    link: https://x.com/MetaboLights
  - icon: fontawesome/brands/bluesky
    link: https://bsky.app/profile/metabolights.bsky.social
extra_css:
  - stylesheets/extra.css
nav:
- index.md
- MHD Common Data Model:
  - mhd_model/index.md
  - Nodes & Relationhips: mhd_model/mhd-nodes.md

markdown_extensions:
# Python Markdown
- abbr:
- attr_list:
- footnotes:
- md_in_html:
- tables:
- admonition:
- def_list:
- toc:
    permalink: true
  # Python Markdown Extensions
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
    linenums: true
    linenums_style: pymdownx-inline
- pymdownx.inlinehilite:
- pymdownx.snippets:
    base_path: [ "mhd", "docs" ]
    check_paths: true
- pymdownx.superfences:
- pymdownx.betterem:
- pymdownx.caret:
- pymdownx.inlinehilite:
- pymdownx.keys:
- pymdownx.mark:
- pymdownx.tilde:

    # pymdownx blocks
- pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    # Custom types
    - info
    - check
    - example
    - success
- pymdownx.blocks.details:
- pymdownx.blocks.tab:
    alternate_style: True
