from mhd_model.shared.cv_definitions import (
    COMMON_CV_DEFINITIONS,
    OTHER_COMMON_CV_DEFINITIONS,
)

CONTROLLED_CV_DEFINITIONS = COMMON_CV_DEFINITIONS


OTHER_CONTROLLED_CV_DEFINITIONS = OTHER_COMMON_CV_DEFINITIONS
