name: Build application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: "Set up Python"
      uses: actions/setup-python@v5.6.0
      with:
        python-version-file: ".python-version"


    - name: Install uv
      uses: astral-sh/setup-uv@v6.3.0
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Set up Python
      run: uv sync

    - id: cz
      name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print Version
      run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

    - name: Build
      run: uv build

    - name: Publish
      run: uv publish -t ${{ secrets.PYPI_TOKEN }}

    - name: Deploy
      run: mkdocs gh-deploy --config-file mkdocs.yml --force
